import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from '@/app/lib/AntdRegistry'
import enUS from 'antd/locale/en_US'
import { ConfigProvider } from 'antd'
import { RefreshProvider } from '@/app/components/refreshProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider locale={enUS}>
          <RefreshProvider>
            <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </RefreshProvider>
        </ConfigProvider>
      </body>
    </html>
  )
}
